#!/bin/bash
#Copyright Omnibond Systems, LLC. All rights reserved.
#
#Terms of Service are located at:
#http://www.cloudycluster.com/termsofservice

export AWS_REGION="eu-central-1"
#Subnet 1b
export AWS_SUBNET="subnet-a233fad9"
# Subnet 1a
export AWS_SUBNET="subnet-fab91093"


export AWS_SECURITY_GROUP="sg-a8da6ec0"
export AWS_VPC="vpc-92e045fb"

export AWS_SOURCE_AMI_CENTOS_6="ami-2bf11444"
export AWS_SOURCE_AMI_CENTOS_7="ami-9bf712f4"
export AWS_SOURCE_AMI_UBUNTU_1404="ami-1ac73275"
#export AWS_SOURCE_AMI_UBUNTU_1504="ami-a8d7c3c9"
#export AWS_SOURCE_AMI_UBUNTU_1510="ami-3e52445f"
export AWS_SOURCE_AMI_UBUNTU_1604="ami-26e70c49"
export AWS_SOURCE_AMI_SLES_12="ami-6bd2ce07"
export AWS_SOURCE_AMI_FEDORA_23="ami-084d5e64"
export AWS_SOURCE_AMI_FEDORA_24="ami-07be4b68"
export AWS_SOURCE_AMI_OPENSUSE_42_1="ami-426a8f2d"
