#!/bin/bash
#Copyright Omnibond Systems, LLC. All rights reserved.
#
#Terms of Service are located at:
#http://www.cloudycluster.com/termsofservice

export AWS_REGION="us-west-2"
export AWS_SUBNET="subnet-c26beeb4"
export AWS_SECURITY_GROUP="sg-ee059788"
export AWS_VPC="vpc-f6412392"
export AWS_SOURCE_AMI_CENTOS_6="ami-80d092b1"
export AWS_SOURCE_AMI_CENTOS_6="ami-05cf2265"
export AWS_SOURCE_AMI_CENTOS_6_PRECONFIG="ami-076a7d66"
export AWS_SOURCE_AMI_CENTOS_7="ami-c7d092f7"
export AWS_SOURCE_AMI_UBUNTU_1404="ami-333f2203"
export AWS_SOURCE_AMI_UBUNTU_1504="ami-a8d7c3c9"
export AWS_SOURCE_AMI_UBUNTU_1510="ami-3e52445f"
export AWS_SOURCE_AMI_UBUNTU_1604="ami-fa82739a"
#export AWS_SOURCE_AMI_SLES_12="ami-37786307"
#export AWS_SOURCE_AMI_SLES_11="ami-6fb6b56f"
export AWS_SOURCE_AMI_SLES_11="ami-99f2aba9"
export AWS_SOURCE_AMI_SLES_12="ami-d2627db3"
export AWS_SOURCE_AMI_FEDORA_22="ami-81362db1"
export AWS_SOURCE_AMI_FEDORA_23="ami-ca2430ab"
export AWS_SOURCE_AMI_FEDORA_24="ami-dcfe3bbc"
export AWS_SOURCE_AMI_OPENSUSE_13_2="ami-01753d31"
export AWS_SOURCE_AMI_OPENSUSE_42_1="ami-aa8e9dcb"
export AWS_SOURCE_AMI_OPENSUSE_13_2_PRECONFIG="ami-256c7b44"
